### PR TITLE
431 new frontend details

### LINKED ISSUE #431: Re-implement web app in the new frontend

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #431

## Description

Removes the entity query from the Admin/Settings page.

Rows on the browse page are now clickable to navigate to the new details page. 

Adds details page, with tree structure. Updates dgraph schema and data loader code so we can use the targeted names here rather than the full description at every level of the tree:
Screenshot 2023-12-13 at 10 29 47 AM

Also adds show all codes toggle:
Screenshot 2023-12-13 at 11 22 42 AM

Copy code to clipboard on click:
Screenshot 2023-12-13 at 11 27 12 AM

This doesn't look exactly like the UI mockups... went with the fastest option using the MUI tree components. There's probably a React library to draw lines for the tree structure rather than the chevron arrows, and I haven't implemented the little side nav, or the table view - thinking we prioritise the Admin interface and if these changes feel important we can come back to them!

### CODE REVIEW

**Comment by lache-melvin** [comment]
Something like this could be an easy win if we like the lines?
Screenshot 2023-12-13 at 12 03 40 PM

**Review by jmbrunskill — APPROVED** [review]
Looks great!

It does want me want to see that table view though, hopefully we have time for that too later.

Some small thoughts...

Would be nice if this didn't have a chevron to show there's nothing underneath
image

Now that we have the more compact view, it would be nice if the bottom properties started open.

image


Would also be nice if the links showed a `link` icon, or at least were in blue to show they are clickable...

image

Was thinking maybe we could have the `Form`, `Form Qualitier` etc etc either in brackets of maybe just a hover over?
image

Not sure if it's better or not. Something to check with Louisa...

**Comment by jmbrunskill** [comment]
image
Would be good to display this a bit nicer...

**Comment by jmbrunskill** [comment]
Small display issue for large trees...
image

**Comment by lache-melvin** [comment]
Thanks James!

> Small display issue for large trees...

[36a59e1](https://github.com/msupply-foundation/unified-codes/pull/441/commits/36a59e15a9a1960f41e9fe06fb0d785b0d1f2df7)

> Would be nice if [leaf nodes] didn't have a chevron to show there's nothing underneath

[eb1a50c](https://github.com/msupply-foundation/unified-codes/pull/441/commits/eb1a50c08d1ba65613a590c4dcc3533fc6136864)

> Would also be nice if the links showed a link icon, or at least were in blue to show they are clickable...

[a405e24](https://github.com/msupply-foundation/unified-codes/pull/441/commits/a405e24d78c9f3e23a77db0ad5c3e007a4c8b2a6)

> Now that we have the more compact view, it would be nice if the bottom properties started open.

[aab5814](https://github.com/msupply-foundation/unified-codes/pull/441/commits/aab581425ce6e22cfada477a7ed3f5208027530a)

On the consumables display... agree its not great, but might be easier to come back to once we know what the tree structure for a consumable will be? Have created a new issue for this (#445)

**Pull request merged**
